metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

metricbeat.modules:
- module: docker
  metricsets:
    - container
    - cpu
    - diskio
    - healthcheck
    - info
    - memory
    - network
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

- module: postgresql
  metricsets:
    - database
    - bgwriter
    - activity
  hosts: ["postgres://admin:password@lakehouse-postgres:5432/lakehouse?sslmode=disable"]
  period: 10s
  enabled: true

output.logstash:
  hosts: ["logstash:5044"]

setup.kibana:
  host: "kibana:5601"
